/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import kontroler.Kontroler;

/**
 *
 * @author Milos
 */
public class FGlavna extends javax.swing.JFrame {

    /**
     * Creates new form FGlavna
     *
     * @param loggedUser
     */
    public FGlavna() {
        initComponents();
        setTitle("Aplikcaija:Škola fudbala, Dobrodošli nazad " + Kontroler.getLoggedUser().getIme());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jmRadSaIgracima = new javax.swing.JMenu();
        jmiUnosNovogIgraca = new javax.swing.JMenuItem();
        jmiPretragaIgraca = new javax.swing.JMenuItem();
        jmTrener = new javax.swing.JMenu();
        jmiPodaciOTreneru = new javax.swing.JMenuItem();
        jmOAplikaciji = new javax.swing.JMenu();
        jmiAutor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikcaija:Skola fudbala");

        jmRadSaIgracima.setText("Rad sa igračima");

        jmiUnosNovogIgraca.setText("Unos novog igrača");
        jmiUnosNovogIgraca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosNovogIgracaActionPerformed(evt);
            }
        });
        jmRadSaIgracima.add(jmiUnosNovogIgraca);

        jmiPretragaIgraca.setText("Pretraga igrača");
        jmiPretragaIgraca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPretragaIgracaActionPerformed(evt);
            }
        });
        jmRadSaIgracima.add(jmiPretragaIgraca);

        jMenuBar1.add(jmRadSaIgracima);

        jmTrener.setText("Trener");

        jmiPodaciOTreneru.setText("Podaci o treneru");
        jmiPodaciOTreneru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPodaciOTreneruActionPerformed(evt);
            }
        });
        jmTrener.add(jmiPodaciOTreneru);

        jMenuBar1.add(jmTrener);

        jmOAplikaciji.setText("O aplikaciji");

        jmiAutor.setText("Autor");
        jmiAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAutorActionPerformed(evt);
            }
        });
        jmOAplikaciji.add(jmiAutor);

        jMenuBar1.add(jmOAplikaciji);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiUnosNovogIgracaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosNovogIgracaActionPerformed
        FIgrac igrac = new FIgrac(this, true, false);
        igrac.setLocationRelativeTo(null);
        igrac.setVisible(true);
    }//GEN-LAST:event_jmiUnosNovogIgracaActionPerformed

    private void jmiPretragaIgracaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPretragaIgracaActionPerformed
        FPretragaIgraca pretragaIgraca = new FPretragaIgraca(this, true);
        pretragaIgraca.setSize(1000, 400);
        pretragaIgraca.setLocationRelativeTo(null);
        pretragaIgraca.setVisible(true);
    }//GEN-LAST:event_jmiPretragaIgracaActionPerformed

    private void jmiAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAutorActionPerformed
        FAutor fAutor = new FAutor(this, true);
        fAutor.setLocationRelativeTo(null);
        fAutor.setVisible(true);
    }//GEN-LAST:event_jmiAutorActionPerformed

    private void jmiPodaciOTreneruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPodaciOTreneruActionPerformed
        FTrener fTrener = new FTrener(this, true);
        fTrener.setLocationRelativeTo(null);
        fTrener.setVisible(true);
    }//GEN-LAST:event_jmiPodaciOTreneruActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmOAplikaciji;
    private javax.swing.JMenu jmRadSaIgracima;
    private javax.swing.JMenu jmTrener;
    private javax.swing.JMenuItem jmiAutor;
    private javax.swing.JMenuItem jmiPodaciOTreneru;
    private javax.swing.JMenuItem jmiPretragaIgraca;
    private javax.swing.JMenuItem jmiUnosNovogIgraca;
    // End of variables declaration//GEN-END:variables
}
