/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Licenca;
import domen.Mesto;
import domen.Trener;
import java.awt.Color;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import komunikacija.KomunikacijaSaServerom;
import kontroler.Kontroler;
import pomoc.Operacija;
import pomoc.StatusOdgovora;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Milos
 */
public class FTrener extends javax.swing.JDialog {

    private int trenerId;

    /**
     * Creates new form FTrener
     */
    public FTrener(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldIme = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPrezime = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldJmbg = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldUlica = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldBroj = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabelUlica = new javax.swing.JLabel();
        jLabelBroj = new javax.swing.JLabel();
        jComboBoxMesto = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxLicenca = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabelIme = new javax.swing.JLabel();
        jLabelPrezime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Podaci o treneru");

        jLabel1.setText("Ime:");

        jLabel2.setText("Prezime:");

        jLabel3.setText("JMBG:");

        jTextFieldJmbg.setEnabled(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Adresa"));

        jLabel4.setText("Ulica:");

        jLabel5.setText("Broj:");

        jLabel6.setText("Mesto:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelUlica)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelBroj, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldUlica, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldBroj, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxMesto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldUlica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jLabelUlica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jComboBoxMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelBroj)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel7.setText("Licenca:");

        jButton1.setText("Sačuvaj izmene");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel7)
                                .addGap(41, 41, 41)
                                .addComponent(jComboBoxLicenca, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldJmbg, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(54, 54, 54)
                                        .addComponent(jTextFieldPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabelIme, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(jLabelPrezime))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabelIme)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabelPrezime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldJmbg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxLicenca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String ime = jTextFieldIme.getText().trim();
        String prezime = jTextFieldPrezime.getText().trim();
        String jmbg = jTextFieldJmbg.getText().trim();
        String ulica = jTextFieldUlica.getText().trim();
        String broj = jTextFieldBroj.getText().trim();
        Mesto mesto = (Mesto) jComboBoxMesto.getSelectedItem();
        Licenca licenca = (Licenca) jComboBoxLicenca.getSelectedItem();
        Trener trener;
        try {
            trener = validacija(ime, prezime, jmbg, ulica, broj, mesto, licenca);
            KlijentskiZahtev kz = new KlijentskiZahtev();
            kz.setAkcija(Operacija.IZMENI_ODO);
            kz.setParametar(trener);
            try {
                KomunikacijaSaServerom.getInstanca().posaljiZahtev(kz);
                ServerskiOdgovor so = KomunikacijaSaServerom.getInstanca().primiOdgovor();
                if (so.getStatus() == StatusOdgovora.OK) {
                    osveziPodatkeOUlogovanomTreneru(trener);
                    JOptionPane.showMessageDialog(this, "Sistem je zapamtio izmene", "Obaveštenje", JOptionPane.INFORMATION_MESSAGE);
                }

            } catch (IOException | ClassNotFoundException ex) {
                Logger.getLogger(FIgrac.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da zapamti izmene nad podacima", "Greška", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBoxLicenca;
    private javax.swing.JComboBox jComboBoxMesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelBroj;
    private javax.swing.JLabel jLabelIme;
    private javax.swing.JLabel jLabelPrezime;
    private javax.swing.JLabel jLabelUlica;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldBroj;
    private javax.swing.JTextField jTextFieldIme;
    private javax.swing.JTextField jTextFieldJmbg;
    private javax.swing.JTextField jTextFieldPrezime;
    private javax.swing.JTextField jTextFieldUlica;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        JOptionPane.showMessageDialog(this, "Sistem je našao podatke o treneru", "Obaveštenje", JOptionPane.INFORMATION_MESSAGE);
        Trener trener = Kontroler.getLoggedUser();
        jTextFieldIme.setText(trener.getIme());
        jTextFieldPrezime.setText(trener.getPrezime());
        jTextFieldJmbg.setText(trener.getJmbg());
        jTextFieldUlica.setText(trener.getUlica());
        jTextFieldBroj.setText(trener.getBroj());
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setAkcija(Operacija.VRATI_SVE_ZA_ODO);
        kz.setParametar(new Mesto());
        try {
            KomunikacijaSaServerom.getInstanca().posaljiZahtev(kz);
            ServerskiOdgovor so = KomunikacijaSaServerom.getInstanca().primiOdgovor();
            if (so.getStatus() == StatusOdgovora.OK) {
                List<Mesto> mesta = (List<Mesto>) so.getOdgovor();
                trenerId = Kontroler.getLoggedUser().getTrenerId();
                for (Mesto mesto : mesta) {
                    jComboBoxMesto.addItem(mesto);
                }
            }

        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(FIgrac.class.getName()).log(Level.SEVERE, null, ex);
        }

        jComboBoxMesto.setSelectedItem(trener.getMesto());
        kz.setAkcija(Operacija.VRATI_SVE_ZA_ODO);
        kz.setParametar(new Licenca());
        try {
            KomunikacijaSaServerom.getInstanca().posaljiZahtev(kz);
            ServerskiOdgovor so = KomunikacijaSaServerom.getInstanca().primiOdgovor();
            if (so.getStatus() == StatusOdgovora.OK) {
                List<Licenca> licence = (List<Licenca>) so.getOdgovor();
                for (Licenca licenca : licence) {
                    jComboBoxLicenca.addItem(licenca);
                }
                jComboBoxLicenca.setSelectedItem(trener.getLicenca());
            }

        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(FIgrac.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private Trener validacija(String ime, String prezime, String jmbg, String ulica, String broj, Mesto mesto, Licenca licenca) throws Exception {
        boolean validnaForma = true;
        if (ime == null || ime.isEmpty()) {
            jLabelIme.setText("Niste uneli ime");
            jLabelIme.setForeground(Color.red);
            validnaForma = false;
        }
        if (prezime == null || prezime.isEmpty()) {
            jLabelPrezime.setText("Niste uneli prezime");
            jLabelPrezime.setForeground(Color.red);
            validnaForma = false;
        }
        if (ulica == null || ulica.isEmpty()) {
            jLabelUlica.setText("Niste uneli ulicu");
            jLabelUlica.setForeground(Color.red);
            validnaForma = false;
        }
        if (broj == null || broj.isEmpty()) {
            jLabelBroj.setText("Niste uneli broj");
            jLabelBroj.setForeground(Color.red);
            validnaForma = false;
        }
        if (!validnaForma) {
            throw new Exception();
        }
        return new Trener(trenerId, jmbg, ime, prezime, ulica, broj, prezime, broj, mesto, licenca);
    }

    private void osveziPodatkeOUlogovanomTreneru(Trener trener) {
        Trener ulogovanTrener = Kontroler.getLoggedUser();
        ulogovanTrener.setIme(trener.getIme());
        ulogovanTrener.setPrezime(trener.getPrezime());
        ulogovanTrener.setJmbg(trener.getJmbg());
        ulogovanTrener.setUlica(trener.getUlica());
        ulogovanTrener.setBroj(trener.getBroj());
        ulogovanTrener.setMesto(trener.getMesto());
        ulogovanTrener.setLicenca(trener.getLicenca());
    }
}
